### ISSUE TITLE
PSCIS data submission error - Photos - Metadata Issues that result in Electronic Submission Framework (ESF) submission "Resizing Error"

### ISSUE THREAD

**Issue by lucy-schick** [NewGraphEnvironment/fish_passage_guidebook#13]
Documenting what we learned from our latest PSICS phase 1 data submission to the province using the ESF portal, which originated from https://github.com/NewGraphEnvironment/fish_passage_fraser_2023_reporting/issues/108 and https://github.com/NewGraphEnvironment/fish_passage_fraser_2023_reporting/issues/113.

When submitting our data we received hundreds of errors regarding photo resizing issues (error message: "The process was unable to resize the attachment photos down to the required size of 1024X1024"), and an example of these errors can be seen here https://github.com/NewGraphEnvironment/fish_passage_fraser_2023_reporting/issues/108#issuecomment-2368330655.

However, our photos were resized to under 1mb in total memory size to meet the submission size criteria. Previously, we have tested adjusting pixel dimension specs of photos to try to avoid the error (https://github.com/NewGraphEnvironment/fish_passage_skeena_2023_reporting/issues/55) but it did not result it fixing the error message. 

Initially we thought the errors were due to using reserved names (upstream, downstream, inlet, outlet, barrel) more than once within the same site (an issue tracked here #12). This was in fact an issue and did result in the reduction of error messages, but interestingly, for each duplicate photo removed, the number of error messages decreased noticeably (ie. it was not a 1 to 1 ratio between the number of duplicates removed and the decrease in error messages). That said, after removing all the duplicate reserve word photos we still had many errors. 

As is the case with many error messages we see from ESF - the error message is not actually indicative of the problem.

The photos that were throwing errors came from a specific time frame and phone (a Samsung SM-A715W). We should note that there were photos taken on this phone during other time periods that did not throw errors. 

To deal with this issue we stripped the photos of their metadata using a custom function we developed specifically for this type of use case - `rfp_photo_metadata_rm`.  More info on this function can be found here https://www.newgraphenvironment.com/rfp/reference/rfp_photo_metadata_rm.html. We tracked which photos were stripped of there metadata in a csv which can be found here https://github.com/NewGraphEnvironment/fish_passage_fraser_2023_reporting/blob/main/data/backup/photo_strip_meta.csv.

We think the issue is very likely related to the `ICC_Profile` of the photos taken with a Sumsung SM-A715W. All the photos that threw a warning when the metadata was stripped (`Warning: ICC_Profile deleted. Image colors may be affected`) had an `ICC_Profile` detected. The screenshot below shows the warnings that were thrown when stripping the metadata.

Stripping the photos of their metadata solved the issue and the submission was accepted. 

![Screen Shot 2024-12-03 at 1 48 11 PM](https://github.com/user-attachments/assets/f12dc077-e6a1-43fc-964a-673070977eb1)

**Comment by NewGraphEnvironment** [comment]
eventually follow up could include identifying the particular `ICC_Profile` that is the issue as it was obviously different from one photo to the next on the same camera with some apparently fine and others (or perhaps just one) not acceptable to the ESF submission portal rules. Closing for now though
